name: Deploy static website to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_53C0FB1F657A4EDC9A967E40C9C947AE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4418787E615A499CA4AD67AE0EAC198F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C794FABAC0B3486EAB51ACD1B3FD6EC1 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: app-ayesha-217
          package: .
